#!/bin/bash
# Quick start examples for SecIDS-CNN continuous live capture

echo "========================================================================"
echo "SecIDS-CNN - Continuous Live Threat Detection Examples"
echo "========================================================================"
echo ""
echo "OPTION 1: Continuous Live Detection (Real-time)"
echo "  Command:"
echo "    sudo python3 SecIDS-CNN/run_model.py live --iface eth0"
echo ""
echo "  Features:"
echo "    - Captures 5-second windows (default)"
echo "    - Processes every 2 seconds"
echo "    - Real-time threat alerts"
echo "    - Cumulative statistics"
echo ""
echo "-----------------------------------------------------------------------"
echo ""
echo "OPTION 2: Custom Window & Interval Settings"
echo "  Command:"
echo "    sudo python3 SecIDS-CNN/run_model.py live --iface eth0 --window 3 --interval 1"
echo ""
echo "  Parameters:"
echo "    --window 3    : Analyze 3-second traffic windows"
echo "    --interval 1  : Process every 1 second"
echo ""
echo "-----------------------------------------------------------------------"
echo ""
echo "OPTION 3: File-Based Detection (Legacy)"
echo "  Command:"
echo "    python3 SecIDS-CNN/run_model.py file datasets/Live-Capture-Test1.csv"
echo ""
echo "  Use for:"
echo "    - Analyzing pre-extracted CSV files"
echo "    - Batch processing"
echo "    - No elevated permissions needed"
echo ""
echo "-----------------------------------------------------------------------"
echo ""
echo "OPTION 4: Find Your Network Interface"
echo "  Command:"
echo "    ifconfig          (or 'ip link show' on modern Linux)"
echo ""
echo "  Look for: eth0, wlan0, en0, en1, etc."
echo ""
echo "========================================================================"
echo ""
echo "SETUP CHECKLIST:"
echo "  [ ] Install Scapy: pip install scapy"
echo "  [ ] Find your interface: ifconfig"
echo "  [ ] Test permissions: sudo tcpdump -i <interface> -c 1"
echo "  [ ] Run continuous detection: sudo python3 SecIDS-CNN/run_model.py live --iface <interface>"
echo ""
echo "========================================================================"
