#!/bin/bash
# Quick Start Guide for Enhanced UI

echo "╔════════════════════════════════════════════════════════════╗"
echo "║       SecIDS-CNN Enhanced UI - Quick Start Guide          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 NEW FEATURES:"
echo "  ✅ Two-panel layout (Menu + Details)"
echo "  ✅ Screen scaling (responsive design)"
echo "  ✅ Two-stage engagement system"
echo "  ✅ Header/Main/Footer structure"
echo ""
echo "🚀 LAUNCH OPTIONS:"
echo ""
echo "Option 1 - Test Enhanced UI (Recommended):"
echo "  cd /home/kali/Documents/Code/SECIDS-CNN"
echo "  .venv_test/bin/python UI/terminal_ui_enhanced.py"
echo ""
echo "Option 2 - Original UI:"
echo "  ./Launchers/secids-ui"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📋 TWO-STAGE SYSTEM:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Stage 1 - SELECTION (View Details):"
echo "  • Use 1-9, 0 to select option"
echo "  • Right panel shows detailed info"
echo "  • Press ENTER to proceed"
echo ""
echo "Stage 2 - ENGAGEMENT (Execute):"
echo "  • Review information"
echo "  • Press ENTER to execute"
echo "  • Press ESC or B to go back"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "⌨️  KEYBOARD SHORTCUTS:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Navigation:"
echo "  1-9, 0    Quick select menu option"
echo "  ↑/↓       Navigate up/down"
echo "  ENTER     View details / Execute"
echo "  ESC/B     Go back"
echo "  Q         Quit"
echo "  H         Help"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📐 LAYOUT:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "┌─────────────────────────────────────────────────────────┐"
echo "│                    HEADER                               │"
echo "│  Title, Version, Timestamp                              │"
echo "├─────────────────┬───────────────────────────────────────┤"
echo "│                 │                                       │"
echo "│   MENU LIST     │     DETAILED INFORMATION            │"
echo "│   (Left 40%)    │     (Right 60%)                     │"
echo "│                 │                                       │"
echo "│ ▶ [1] Option 1  │  Title: Option 1                    │"
echo "│   [2] Option 2  │  Description: ...                   │"
echo "│   [3] Option 3  │  Details: • Feature 1               │"
echo "│   ...           │           • Feature 2               │"
echo "│                 │  Sub-options: 1. Action A           │"
echo "│                 │               2. Action B           │"
echo "├─────────────────┴───────────────────────────────────────┤"
echo "│                    FOOTER                               │"
echo "│  ENTER: View Details │ ESC/B: Back │ Q: Quit          │"
echo "└─────────────────────────────────────────────────────────┘"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "🔧 TERMINAL REQUIREMENTS:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Minimum:    80x24 characters"
echo "  Recommended: 120x30 characters"
echo "  Optimal:     140x40 characters"
echo ""
echo "  Check your terminal size:"
echo "    tput cols && tput lines"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION:"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "  Full report: Reports/ENHANCED_UI_IMPLEMENTATION.md"
echo "  Original UI backup: UI/terminal_ui_v1_backup.py"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
